###
GET http://localhost:3100/api/services

###
POST http://localhost:3100/api/services
Content-Type: application/json

{
    "description": "very good membership",
    "name": "Premium",
    "price": "599.99"
}


###
GET http://localhost:3100/api/users
###
DELETE http://localhost:3100/api/services/62625d155db940400920cf3f

###
POST http://localhost:3100/api/users
Content-Type: application/json

{
    "email": "labas@krabas.lt",
    "name": "labas",
    "surname": "krabas",
    "service_id": "1.99"
}

