###
GET http://localhost:3100/api/services

###
POST http://localhost:3100/api/services
Content-Type: application/json

{
    "description": "very good membership",
    "name": "very nice",
    "price": "1.99"
}

###
DELETE http://localhost:3100/api/services/6261027724d902caea878f94